"""users table

Revision ID: 090b3ebee1ec
Revises: 
Create Date: 2024-05-14 20:34:24.178253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090b3ebee1ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    if not conn.dialect.has_table(conn, "user"):
        op.create_table(
            'user',
            sa.Column('id', sa.Integer, primary_key=True),
            sa.Column('username', sa.String(64), nullable=False),
            sa.Column('email', sa.String(64), nullable=False, unique=True),
            sa.Column('password_hash', sa.String(256), nullable=False),
            sa.Column('points', sa.Integer, nullable=False),
            sa.Column('status', sa.String(7), nullable=False),
        )

    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_user_id'), ['user_id'], unique=False)

    op.create_table('threads',
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_table('responses',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('response_id', sa.String(length=100), nullable=False),
    sa.Column('response_no', sa.Integer(), nullable=False),
    sa.Column('responder_id', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    op.drop_table('threads')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))

    op.drop_table('post')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    # ### end Alembic commands ###
