"""empty message

Revision ID: ad7163062f48
Revises: 090b3ebee1ec
Create Date: 2024-05-16 20:38:51.331922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7163062f48'
down_revision = '090b3ebee1ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    op.drop_table('threads')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=500),
               existing_nullable=False)

    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_name', sa.String(length=140), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.drop_column('thread_name')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)

    op.create_table('threads',
    sa.Column('thread_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_table('responses',
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('thread_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('response_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('response_no', sa.INTEGER(), nullable=False),
    sa.Column('responder_id', sa.VARCHAR(length=8), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    # ### end Alembic commands ###
